59 lukovio hero next 2 sections
lukov-io/lukov.io pull request #5
Opened 2022-11-07 11:14 UTC by D1maSf

2022-11-14 06:48 UTC, timonbandit requested changes
Please check ipad resolution

2022-11-14 06:48 UTC, timonbandit commented on index.html
> +    <link rel="stylesheet" href="/scss/index.scss">
Maybe 1 stylesheet is enough?

2022-11-14 06:48 UTC, timonbandit commented on index.html
> +                        <i class="fa-brands fa-behance"></i>
icons are links
wrap with <a>

2022-11-14 06:48 UTC, timonbandit commented on js/main.js
> +
you can remove this

2022-11-14 06:48 UTC, timonbandit commented on scss/index.scss
> +//include files//
comments in SCSS looks like
```
/* comment */
// comment
```

2022-11-17 15:40 UTC, timonbandit commented on index.html
> +      </div>
I think this block should be a link.
Because now hover is looks weird. 
Better to have an entire block clickable

2022-11-17 15:40 UTC, timonbandit commented on index.html
> +
```suggestion
```

2022-11-23 07:36 UTC, yuri-kovalev approved these changes

2022-11-23 07:37 UTC, merged